# Generated by Django 5.0.2 on 2024-02-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO app_year (year, fair_share) VALUES (2024, 1000);"),
    ]
