# Generated by Django 5.0.2 on 2024-02-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_openproductmodel_opensourceecosystem_organization_and_more'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO app_openproductmodel (name) VALUES ('DOSP');"),
        migrations.RunSQL("INSERT INTO app_openproductmodel (name) VALUES ('Open Core');"),
        migrations.RunSQL("INSERT INTO app_openproductmodel (name) VALUES ('Hybrid');"),
        migrations.RunSQL("INSERT INTO app_openproductmodel (name) VALUES ('Other');"),
    ]
