# Generated by Django 5.0.2 on 2024-02-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_init_more_model_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='openproduct',
            name='img_src',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='opensourceecosystem',
            name='img_src',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='opensourceproject',
            name='img_src',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='img_src',
            field=models.URLField(default=''),
        ),
    ]
