# Generated by Django 5.0.2 on 2024-02-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_openproduct_owner_and_more'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('npmjs.org','https://github.com/npm.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('proxy.golang.org','https://github.com/golang.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('hub.docker.com','https://github.com/docker.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('nuget.org','https://github.com/nuget.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('pypi.org','https://github.com/pypi.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('repo1.maven.org','https://github.com/maven-central.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('packagist.org','https://github.com/packagist.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('rubygems.org','https://github.com/rubygems.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('crates.io','https://github.com/rust-lang.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('cocoapod.org','https://github.com/cocoapods.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('bower.io','https://github.com/bower.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('pub.dev','https://github.com/dart-lang.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('metacpan.org','https://github.com/metacpan.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('alpine','https://github.com/alpinelinux.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('github actions','https://github.com/actions.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('cran.r-project.org','https://github.com/r-project-org.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('clojars.org','https://github.com/clojars.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('conda-forge.org','https://github.com/conda-forge.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('anaconda.org','https://github.com/Anaconda.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('hackage.haskell.org','https://github.com/haskell-infra.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('hex.pm','https://github.com/hexpm.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('juliahub.com','https://github.com/JuliaRegistries.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('spack.io','https://github.com/spack.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('pkg.adelielinux.org','https://github.com/AdelieLinux.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('forge.puppet.com','https://github.com/puppet.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('swiftpackageindex.com','https://github.com/SwiftPackageIndex.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('formulae.brew.sh','https://github.com/homebrew.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('deno.land','https://github.com/denoland.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('package.elm-lang.org','https://github.com/elm.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('pkgs.racket-lang.org','https://github.com/racket-lang.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('vcpkg.io','https://github.com/vcpkg.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('bioconductor.org','https://github.com/Bioconductor.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('carthage','https://github.com/Carthage.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('postmarketos','https://github.com/postmarketos.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('elpa.gnu.org','https://github.com/emacs.png');"),
        migrations.RunSQL("INSERT INTO app_opensourceecosystem (name, img_src) VALUES ('elpa.nongnu.org','https://github.com/emacs.png');"),
    ]
