# Generated by Django 5.0.2 on 2024-02-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_init_even_more_model_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fairshare',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='ndevs',
        ),
        migrations.AddField(
            model_name='fairshare',
            name='ndevs',
            field=models.IntegerField(null=True),
        ),
    ]
