# Generated by Django 5.0.2 on 2024-03-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('app', '0009_organization_current_fair_share_and_more'), ('app', '0010_organization_slug'), ('app', '0011_organization_nproducts_organization_nprojects')]

    dependencies = [
        ('app', '0008_remove_fairshare_amount_remove_organization_ndevs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='current_fair_share',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='member_since',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='organization',
            name='nproducts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='nprojects',
            field=models.IntegerField(default=0),
        ),
    ]
