# Generated by Django 5.0.2 on 2024-03-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_added_homepage_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='opensourceecosystem',
            name='nmaintainers',
            field=models.IntegerField(default=0),
        ),
    ]
